[phases.setup]
# Add Python & pip so "python -m venv" works during build, plus CBC solver
nixPkgs = ['python311', 'python311Packages.pip', 'cbc']

[phases.build]
# Explicitly install dependencies and verify consistency
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "pip check"  # Ensures no dependency conflicts
]

[phases.install]
# No additional packages needed here
nixPkgs = []
