[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'cbc']

[phases.build]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "pip check"  # Verify dependency consistency
]

[phases.install]
nixPkgs = []  # No additional pkgs needed here
